version: '3.7'

services:
  db:
    image: postgres:13.3
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
  django_app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - static:/static
      - media:/media
    env_file: .env
    depends_on: 
      - db
  nginx:
    build: ./nginx
    volumes: 
      - static:/static
      - media:/media
    ports:
      - "80:80"
    depends_on:
      - django_app

volumes:
  static:
  media:
  postgres_data: